name: Build

on: 
  # Trigger on push to main, dev
  push:
    branches: [ main, dev ]
  # Trigger on any PR
  pull_request:  

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.100"
          
      - name: Cache Unity project   
        uses: actions/cache@v3
        with:
          path: ./Library
          key: Library-UnityNetcodePatcher
          restore-keys: |
            Library-UnityNetcodePatcher-
            Library-

      - name: Restore Unity project  
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          buildMethod: UnityBuilderAction.RestoreScript.Restore
      
      - name: Tree assembly source paths  
        run: |
          sudo apt-get install tree
          tree ./Library/ScriptAssemblies/
          ls /home/runner/work/_temp/_github_home
          tree /home/runner/work/_temp/_github_home/opt/unity/Editor/Data/Managed
          
      - name: Build solution
        run: dotnet build /p:UnityEditorDir=/opt/Unity/Editor
  
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: "./NetcodePatcher.*/bin/*/*.nupkg"