name: Build

on: 
  # Trigger on push to main, dev
  push:
    branches: [ main, dev ]
  # Trigger on any PR
  pull_request:  

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
          submodules: recursive

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.100"
          
      - name: Cache Unity project   
        uses: actions/cache@v3
        with:
          path: ./UnityProject/Library
          key: Library-UnityNetcodePatcher
          restore-keys: |
            Library-UnityNetcodePatcher-
            Library-

      - name: Restore Unity project  
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ./UnityProject
          targetPlatform: WebGL
          buildMethod: UnityBuilderAction.RestoreScript.Restore
      
      - name: Tree assembly source paths  
        run: |
          sudo apt-get install tree
          tree ./UnityProject//Library/ScriptAssemblies/
          tree ./UnityProject/UnityEditor
          
      - name: Build solution
        shell: bash
        run: |
          dotnet pack -p:UnityEditorDir="${{ github.workspace }}/UnityProject/UnityEditor"
  
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: "./NetcodePatcher*/bin/*/*.nupkg"